fun main() {
    val list = DoublyLinkedList<Int>()
    list.push(14)
    list.push(12)
    println(list.head)
    println(list.head?.prev)
    println(list.head?.next)
    println(list.head?.next?.prev)
    list.addTail(10)
    list.push(11)
    list.addTail(18)
    println(list.head)
    list.pop()
    println(list.head)
    println(list.head?.prev)
    list.delTail()
    println(list.head)
    list.delTail()
    println(list.head)
}